// <auto-generated />
using BonjeMetBonten.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonjeMetBonten.Migrations
{
    [DbContext(typeof(VideoDbContext))]
    partial class VideoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BonjeMetBonten.Models.Koppel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnderwerpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OnderwerpId");

                    b.HasIndex("VideoId");

                    b.ToTable("Koppels");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            OnderwerpId = -4,
                            VideoId = -1
                        },
                        new
                        {
                            Id = -2,
                            OnderwerpId = -3,
                            VideoId = -2
                        },
                        new
                        {
                            Id = -3,
                            OnderwerpId = -2,
                            VideoId = -3
                        },
                        new
                        {
                            Id = -4,
                            OnderwerpId = -7,
                            VideoId = -3
                        },
                        new
                        {
                            Id = -5,
                            OnderwerpId = -3,
                            VideoId = -4
                        },
                        new
                        {
                            Id = -6,
                            OnderwerpId = -10,
                            VideoId = -5
                        },
                        new
                        {
                            Id = -7,
                            OnderwerpId = -8,
                            VideoId = -6
                        },
                        new
                        {
                            Id = -8,
                            OnderwerpId = -9,
                            VideoId = -6
                        },
                        new
                        {
                            Id = -9,
                            OnderwerpId = -8,
                            VideoId = -7
                        },
                        new
                        {
                            Id = -10,
                            OnderwerpId = -8,
                            VideoId = -8
                        },
                        new
                        {
                            Id = -11,
                            OnderwerpId = -9,
                            VideoId = -8
                        },
                        new
                        {
                            Id = -12,
                            OnderwerpId = -10,
                            VideoId = -8
                        },
                        new
                        {
                            Id = -13,
                            OnderwerpId = -1,
                            VideoId = -9
                        },
                        new
                        {
                            Id = -14,
                            OnderwerpId = -1,
                            VideoId = -10
                        },
                        new
                        {
                            Id = -15,
                            OnderwerpId = -3,
                            VideoId = -11
                        },
                        new
                        {
                            Id = -16,
                            OnderwerpId = -6,
                            VideoId = -11
                        },
                        new
                        {
                            Id = -17,
                            OnderwerpId = -6,
                            VideoId = -12
                        },
                        new
                        {
                            Id = -18,
                            OnderwerpId = -7,
                            VideoId = -13
                        },
                        new
                        {
                            Id = -19,
                            OnderwerpId = -2,
                            VideoId = -14
                        },
                        new
                        {
                            Id = -20,
                            OnderwerpId = -5,
                            VideoId = -14
                        },
                        new
                        {
                            Id = -21,
                            OnderwerpId = -6,
                            VideoId = -14
                        },
                        new
                        {
                            Id = -22,
                            OnderwerpId = -7,
                            VideoId = -14
                        },
                        new
                        {
                            Id = -23,
                            OnderwerpId = -3,
                            VideoId = -15
                        },
                        new
                        {
                            Id = -24,
                            OnderwerpId = -3,
                            VideoId = -16
                        },
                        new
                        {
                            Id = -25,
                            OnderwerpId = -3,
                            VideoId = -17
                        });
                });

            modelBuilder.Entity("BonjeMetBonten.Models.Onderwerp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Onderwerpen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Omschrijving = "Stamina"
                        },
                        new
                        {
                            Id = -2,
                            Omschrijving = "Side Kick"
                        },
                        new
                        {
                            Id = -3,
                            Omschrijving = "Ontwijking van gevaar"
                        },
                        new
                        {
                            Id = -4,
                            Omschrijving = "Back Fist"
                        },
                        new
                        {
                            Id = -5,
                            Omschrijving = "Back Kick"
                        },
                        new
                        {
                            Id = -6,
                            Omschrijving = "Front Kick"
                        },
                        new
                        {
                            Id = -7,
                            Omschrijving = "RoundHouse Kick"
                        },
                        new
                        {
                            Id = -8,
                            Omschrijving = "Uppercut"
                        },
                        new
                        {
                            Id = -9,
                            Omschrijving = "The Jab"
                        },
                        new
                        {
                            Id = -10,
                            Omschrijving = "The Hook"
                        });
                });

            modelBuilder.Entity("BonjeMetBonten.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Link = "https://www.youtube.com/embed/gNd5c2C8Doc",
                            Titel = "Spinning Back Fist"
                        },
                        new
                        {
                            Id = -2,
                            Link = "https://www.youtube.com/embed/NMGFwBM7Uo4",
                            Titel = "Shooting"
                        },
                        new
                        {
                            Id = -3,
                            Link = "https://www.youtube.com/embed/Mgb8wujuit0",
                            Titel = "Side Kick 4.3"
                        },
                        new
                        {
                            Id = -4,
                            Link = "https://www.youtube.com/embed/Nz7mAvVysrI",
                            Titel = "Slipping and Evading 3.6"
                        },
                        new
                        {
                            Id = -5,
                            Link = "https://www.youtube.com/embed/ocqFWvSVOLc",
                            Titel = "The Hook 3.2"
                        },
                        new
                        {
                            Id = -6,
                            Link = "https://www.youtube.com/embed/uVsfBos88CI",
                            Titel = "The Jab 3.1"
                        },
                        new
                        {
                            Id = -7,
                            Link = "https://www.youtube.com/embed/QoL2fQDCPas",
                            Titel = "The Uppercut 3.3"
                        },
                        new
                        {
                            Id = -8,
                            Link = "https://www.youtube.com/embed/1Wzi6j1REWI",
                            Titel = "Deadly Combinations 3.4"
                        },
                        new
                        {
                            Id = -9,
                            Link = "https://www.youtube.com/embed/lDMZximoLmk",
                            Titel = "Uithoudingsvermogen(NL) 1.4"
                        },
                        new
                        {
                            Id = -10,
                            Link = "https://www.youtube.com/embed/G5mJKBT4HH4",
                            Titel = "Small series of different exercises for combat stamina"
                        },
                        new
                        {
                            Id = -11,
                            Link = "https://www.youtube.com/embed/vr4Mwf0Ymm8",
                            Titel = "Voetenwerk (NL) 1.3"
                        },
                        new
                        {
                            Id = -12,
                            Link = "https://www.youtube.com/embed/iygxaot9Vms",
                            Titel = "Flying Front Kick 4.8"
                        },
                        new
                        {
                            Id = -13,
                            Link = "https://www.youtube.com/embed/cRX5-wS4M8s",
                            Titel = "Roundhouse kick 4.2"
                        },
                        new
                        {
                            Id = -14,
                            Link = "https://www.youtube.com/embed/aRGVRt-i9ww",
                            Titel = "Vicious Combinations 4.6"
                        },
                        new
                        {
                            Id = -15,
                            Link = "https://www.youtube.com/embed/Sa3_tBJXSSg",
                            Titel = "Jo Bonten - Wat te doen bij een terroristische aanslag"
                        },
                        new
                        {
                            Id = -16,
                            Link = "https://www.youtube.com/embed/SJ6gUtVuMWE",
                            Titel = "Zo SCHUIL je voor KOGELS | Man Bijt Hond | KIJK"
                        },
                        new
                        {
                            Id = -17,
                            Link = "https://www.youtube.com/embed/EvJSNf75Ouw",
                            Titel = "Headbutt"
                        });
                });

            modelBuilder.Entity("BonjeMetBonten.Models.Koppel", b =>
                {
                    b.HasOne("BonjeMetBonten.Models.Onderwerp", "Onderwerp")
                        .WithMany()
                        .HasForeignKey("OnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BonjeMetBonten.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onderwerp");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
